python ReweightingHistograms/CreateReweightingHistogram.py --file raw_plots.root --numerator LowMuData --denomenator PythiaJetJet --histogramName EventCount --outputName LowMuData_PythiaJetJet_Count_Reweight
python ReweightingHistograms/CreateReweightingHistogram.py --file raw_plots.root --numerator LowMuData --denomenator PythiaJetJetHardScatter --histogramName EventCount --outputName LowMuData_PythiaJetJetHardScatter_Count_Reweight
python ReweightingHistograms/CreateReweightingHistogram.py --file raw_plots.root --numerator LowMuDataTightIso --denomenator PythiaJetJetTightIso --histogramName EventCount --outputName LowMuDataTightIso_PythiaJetJetTightIso_Count_Reweight
python ReweightingHistograms/CreateReweightingHistogram.py --file raw_plots.root --numerator LowMuDataTightIso --denomenator PythiaJetJetHardScatterTightIso --histogramName EventCount --outputName LowMuDataTightIso_PythiaJetJetHardScatterTightIso_Count_Reweight
python ReweightingHistograms/CreateReweightingHistogram.py --file raw_plots.root --numerator LowMuData --denomenator SinglePion --histogramName trkCount --outputName LowMuData_SinglePion_TrkCount_Reweight
python ReweightingHistograms/CreateReweightingHistogram.py --file raw_plots.root --numerator LowMuDataTightIso --denomenator SinglePion --histogramName trkCount --outputName LowMuDataTightIso_SinglePion_TrkCount_Reweight

#python ReweightingHistograms/CreateReweightingHistogram.py --file CountReweightedPlots.root --numerator LowMuData --denomenator PythiaJetJet --histogramName TrackPtSpectrum__Inclusive_Eta_0 --outputName PtSpectrumReweightLowMuDataOverPythiaJetJet_Eta0
#python ReweightingHistograms/CreateReweightingHistogram.py --file CountReweightedPlots.root --numerator LowMuData --denomenator PythiaJetJet --histogramName TrackPtSpectrum__Inclusive_Eta_1 --outputName PtSpectrumReweightLowMuDataOverPythiaJetJet_Eta1
#python ReweightingHistograms/CreateReweightingHistogram.py --file CountReweightedPlots.root --numerator LowMuData --denomenator PythiaJetJet --histogramName TrackPtSpectrum__Inclusive_Eta_2 --outputName PtSpectrumReweightLowMuDataOverPythiaJetJet_Eta2
#python ReweightingHistograms/CreateReweightingHistogram.py --file CountReweightedPlots.root --numerator LowMuData --denomenator PythiaJetJet --histogramName TrackPtSpectrum__Inclusive_Eta_3 --outputName PtSpectrumReweightLowMuDataOverPythiaJetJet_Eta3
#python ReweightingHistograms/CreateReweightingHistogram.py --file CountReweightedPlots.root --numerator LowMuData --denomenator PythiaJetJet --histogramName TrackPtSpectrum__Inclusive_Eta_4 --outputName PtSpectrumReweightLowMuDataOverPythiaJetJet_Eta4

#python ReweightingHistograms/CreateReweightingHistogram.py --file PtBinReweightedExceptSinglePion.root --numerator LowMuData --denomenator SinglePion --histogramName TrackPtSpectrum__Inclusive_Eta_0 --outputName PtSpectrumReweightLowMuDataOverSinglePion_Eta0
#python ReweightingHistograms/CreateReweightingHistogram.py --file PtBinReweightedExceptSinglePion.root --numerator LowMuData --denomenator SinglePion --histogramName TrackPtSpectrum__Inclusive_Eta_1 --outputName PtSpectrumReweightLowMuDataOverSinglePion_Eta1
#python ReweightingHistograms/CreateReweightingHistogram.py --file PtBinReweightedExceptSinglePion.root --numerator LowMuData --denomenator SinglePion --histogramName TrackPtSpectrum__Inclusive_Eta_2 --outputName PtSpectrumReweightLowMuDataOverSinglePion_Eta2
#python ReweightingHistograms/CreateReweightingHistogram.py --file PtBinReweightedExceptSinglePion.root --numerator LowMuData --denomenator SinglePion --histogramName TrackPtSpectrum__Inclusive_Eta_3 --outputName PtSpectrumReweightLowMuDataOverSinglePion_Eta3
#python ReweightingHistograms/CreateReweightingHistogram.py --file PtBinReweightedExceptSinglePion.root --numerator LowMuData --denomenator SinglePion --histogramName TrackPtSpectrum__Inclusive_Eta_4 --outputName PtSpectrumReweightLowMuDataOverSinglePion_Eta4


#python ReweightingHistograms/CreateReweightingHistogram.py --file CountReweightedPlots.root --numerator LowMuData --denomenator PythiaJetJetPionsReweighted --histogramName TrackPtSpectrum__Inclusive_Eta_0 --outputName PtSpectrumReweightLowMuDataOverPythiaJetJetPionsReweighted_Eta0
#python ReweightingHistograms/CreateReweightingHistogram.py --file CountReweightedPlots.root --numerator LowMuData --denomenator PythiaJetJetPionsReweighted --histogramName TrackPtSpectrum__Inclusive_Eta_1 --outputName PtSpectrumReweightLowMuDataOverPythiaJetJetPionsReweighted_Eta1
#python ReweightingHistograms/CreateReweightingHistogram.py --file CountReweightedPlots.root --numerator LowMuData --denomenator PythiaJetJetPionsReweighted --histogramName TrackPtSpectrum__Inclusive_Eta_2 --outputName PtSpectrumReweightLowMuDataOverPythiaJetJetPionsReweighted_Eta2
#python ReweightingHistograms/CreateReweightingHistogram.py --file CountReweightedPlots.root --numerator LowMuData --denomenator PythiaJetJetPionsReweighted --histogramName TrackPtSpectrum__Inclusive_Eta_3 --outputName PtSpectrumReweightLowMuDataOverPythiaJetJetPionsReweighted_Eta3
#python ReweightingHistograms/CreateReweightingHistogram.py --file CountReweightedPlots.root --numerator LowMuData --denomenator PythiaJetJetPionsReweighted --histogramName TrackPtSpectrum__Inclusive_Eta_4 --outputName PtSpectrumReweightLowMuDataOverPythiaJetJetPionsReweighted_Eta4

